### ISSUE TITLE
Error in gsheet2txt: could not find function "%>%"

### ISSUE THREAD

**Issue by jbullock35** [maxconway/gsheet#1]
I'm using R 3.1.0 for Windows x86_64 with gsheet 0.1.0.  I've tried `gsheet2tbl` and `gsheet2text` on multiple URLs.  I always get the same error:

```
> myURL   <- 'https://docs.google.com/spreadsheets/d/1kOjhClhsG_FsxN123__M9xrcaeTFZOL6K0-or9_P53Q'
> myTable <- gsheet2tbl(myURL)

Error in gsheet::gsheet2text(url, format = "csv", sheetid = sheetid) : could not find function "%>%"
```

Here is the `traceback()` output:

15: gsheet::gsheet2text(url, format = "csv", sheetid = sheetid)
14: textConnection(text, encoding = "UTF-8")
13: read.table(file = file, header = header, sep = sep, quote = quote, 
        dec = dec, fill = fill, comment.char = comment.char, ...)
12: read.csv(text = gsheet::gsheet2text(url, format = "csv", sheetid = sheetid), 
        stringsAsFactors = FALSE)
11: is.data.frame(data)
10: eval(expr, envir, enclos)
9: eval(assertion, env)
8: doTryCatch(return(expr), name, parentenv, handler)
7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
6: tryCatchList(expr, classes, parentenv, handlers)
5: tryCatch({
       eval(assertion, env)
   }, assertError = function(e) {
       structure(FALSE, msg = e$message)
   })
4: see_if(..., env = env)
3: assert_that(is.data.frame(data))
2: dplyr::tbl_df(read.csv(text = gsheet::gsheet2text(url, format = "csv", 
       sheetid = sheetid), stringsAsFactors = FALSE)) at gsheet2tbl.R#27
1: gsheet2tbl(myURL)

Is there anything that I can do?

**Comment by maxconway** [comment]
Do: `install.packages('dplyr')` and see if that solves the problem.

Dplyr is listed as a requirement so it should be installed automatically, but if something went wrong and it wasn't, then this is the error I'd expect.

**Comment by jbullock35** [comment]
> Do: install.packages('dplyr') and see if that solves the problem.

Thank you -- this helped.

dplyr was already installed.  But further inspection shows that `library(gsheet)` doesn't automatically load the dplyr package, at least on my machine.  If I manually load dplyr via `library(dplyr)` and then re-run the example above, the `could not find function "%>%"` error goes away.

By the way: I'm finding the same sort of issue for the rvest package.  I have it installed, but it isn't loaded automatically when I run `library(gsheet)`.  Specifically, this is what happens:

```
> library(dplyr)
> library(gsheet)
> myURL   <- 'https://docs.google.com/spreadsheets/d/1kOjhClhsG_FsxN123__M9xrcaeTFZOL6K0-or9_P53Q'
> myTable <- gsheet2tbl(myURL)

Error in function_list[[i]](value) : could not find function "html_nodes"
```

But adding `library(rvest)` to the start of this section of code takes care of that problem.  And after that, everything works well.

**Comment by maxconway** [comment]
I can't replicate this on my machine, but I suspect that this is due to a bug in a check I added in the latest development version.
I've pushed a patch for this bug, so do `devtools::install_github("maxconway/gsheet")` and hopefully everything should work correctly.

**Comment by jbullock35** [comment]
> I've pushed a patch for this bug, so do devtools::install_github("maxconway/gsheet") and hopefully everything should work correctly.

Yes, that seems to have taken care of it.  Thank you.
