### ISSUE TITLE
which version of R?

### ISSUE THREAD

**Issue by sarahcn** [maxconway/gsheet#10]
Which versions of R work with gsheets? I've tried to install the package with R version 3.3.2, R version 3.3.0, and R version 3.2.2, but each time get the error message

Warning message:
package 'gsheets' is not available (for R version XXX)

Thanks!

**Comment by sarahcn** [comment]
I'm sorry, please disregard. I was trying to do 

install.packages("gsheets")

instead of

install.packages("gsheet")

**Comment by maxconway** [comment]
No worries, it happens to us all :)
