### ISSUE TITLE
Error message when installing from github.

### ISSUE THREAD

**Issue by jjcad** [maxconway/gsheet#2]
This error message shows when trying to run the functions from the version available on CRAN. The error message also shows and causes the package to fail to be installed when installed from github.

Error in function (type, msg, asError = TRUE)  : <not set>

> sessionInfo()
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8  
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.7.0

loaded via a namespace (and not attached):
[1] httr_0.6.1     RCurl_1.95-4.3 stringr_0.6.2

**Comment by maxconway** [comment]
I can't replicate that error, but after opening R fresh, and reinstalling and loading gsheet, my sessionInfo looks like this:
the

> R version 3.2.0 (2015-04-16)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.2 LTS
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C  
>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8  
>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8  
>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C  
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C  
> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods  
> [7] base     
> 
> loaded via a namespace (and not attached):
>  [1] httr_0.6.1     selectr_0.2-3  magrittr_1.5   assertthat_0.1
>  [5] parallel_3.2.0 DBI_0.3.1      tools_3.2.0    RCurl_1.95-4.5
>  [9] dplyr_0.4.1    Rcpp_0.11.5    stringr_0.6.2  rvest_0.2.0  
> [13] bitops_1.0-6   XML_3.98-1.1  

I notice that your 'loaded via namespace' does not include rvest, which could be a possible source of the problem. 

Could you try reinstalling rvest and see if that solves the problem?

**Comment by jjcad** [comment]
I'm still getting an the error even with rvest attached. Weird, huh?

```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] selectr_0.2-3  rvest_0.2.0    devtools_1.7.0

loaded via a namespace (and not attached):
[1] httr_0.6.1       magrittr_1.5     tools_3.2.0      rstudioapi_0.3.1
[5] RCurl_1.95-4.3   stringr_0.6.2    XML_3.98-1.1     tcltk_3.2.0     
> install_github('maxconway/gsheet')
Downloading github repo maxconway/gsheet@master
Error in function (type, msg, asError = TRUE)  : <not set>
```

**Comment by maxconway** [comment]
I've set up travis build integration to make sure I'm checking on an entirely fresh system, and tried with old, current, and new versions of stringr and rvest and I haven't managed to replicate this.
I did find a couple of other problems, though, which led to me refactoring the namespace organisation.
There's a chance that if you reinstall from github you might find that I've solved your issue by accident.

**Comment by jjcad** [comment]
Sorry I wasn't able to get back to this as soon as I would have liked. I did just install it again and everything seems to work well. Thanks for making the package!

**Comment by maxconway** [comment]
oh, excellent. It actually didn't work properly for me for a while, I think
possibly something to do with google drive's url format changing slightly
for multi-sheet documents. When I get a chance I'll arrange some sort of
continuous testing setup.
