### ISSUE TITLE
Error Installing 

### ISSUE THREAD

**Issue by agogodavid** [maxconway/gsheet#3]
I dont know if this is based on my configuration or the package...

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
- deb: libxml2-dev (Debian, Ubuntu, etc)
- rpm: libxml2-devel (Fedora, CentOS, RHEL)
- csw: libxml2_dev (Solaris)
  If libxml-2.0 is already installed, check that 'pkg-config' is in your
  PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
  is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
  R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
  --------------------------------------------------------------------
  ERROR: configuration failed for package ‘xml2’
  - removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/xml2’
    Warning in install.packages :
    installation of package ‘xml2’ had non-zero exit status
    ERROR: dependency ‘XML’ is not available for package ‘selectr’
  - removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/selectr’
    Warning in install.packages :
    installation of package ‘selectr’ had non-zero exit status
    ERROR: dependencies ‘xml2’, ‘selectr’ are not available for package ‘rvest’
  - removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/rvest’
    Warning in install.packages :
    installation of package ‘rvest’ had non-zero exit status
    ERROR: dependencies ‘rvest’, ‘xml2’ are not available for package ‘gsheet’
  - removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/gsheet’
    Warning in install.packages :
    installation of package ‘gsheet’ had non-zero exit status

My details:

platform       x86_64-pc-linux-gnu  
arch           x86_64  
os             linux-gnu  
system         x86_64, linux-gnu  
status  
major          3  
minor          2.3  
year           2015  
month          12  
day            10  
svn rev        69752  
language       R  
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree

**Comment by maxconway** [comment]
Looks to me like you're missing libxml, which is a dependency for xml2, which this package needs.
Try `sudo apt-get install libxml2-dev` (or the equivalent for OS) in your terminal, and install again?
If that doesn't work, try installing xml2 manually and seeing if it gives you a more helpful error message.
Tell me how it goes :)
