### ISSUE TITLE
Problems running script.

### ISSUE THREAD

**Issue by santiagobe** [maxconway/gsheet#4]
Im trying to import a google sheet using gsheet2tbl(URL), it does work in R, but while tryin to use it like a script in powerbi callin for R,  i get this error.
Error in as.vector(x, "list") : 
  cannot coerce type 'environment' to vector of type 'list'
Calls: gsheet2tbl ... <Anonymous> -> lapply -> as.list -> as.list.default

Does it makes sense for you?. any idea where the problem could be?

**Comment by maxconway** [comment]
Hi,
It sounds like a bug in Power BI, in particular it's interaction with plyr. Have you seen other similar errors?
If I were you I'd make sure all your packages are up to date, and if you still have the issue, try contacting Power BI support. 
Could you tell me what they tell you, in case it's something I can fix after all?
Thanks
