### ISSUE TITLE
new "unable to retrieve document" errors

### ISSUE THREAD

**Issue by jbullock35** [maxconway/gsheet#6]
Within the last three days, old commands that once worked have stopped working.  No matter what I try, `gsheet2text` and `gsheet2tbl` produce this error: `Unable to retrieve document. Is 'share by link' enabled for this sheet?`  

Here is a minimal example:
`myURL <- 'docs.google.com/spreadsheets/d/1Rv5mJmLIKdF5ZME6jsU4_jzAGxkLpBiFOvAVWe763KI'
gsheet2text(myURL, format = 'csv')`

I've tried this on two separate Win7 machines, running R 3.1.0 and R 3.2.5, with both the CRAN version of gsheet (v0.2.1) and the current GitHub version.  I get the error in every case.

Is there anything that I should try to fix the problem?

**Comment by scrogster** [comment]
I'm experiencing the same problem. Last worked properly 3 days ago. Here's an example and sessionInfo() output from R.

> library(gsheet)
> papers<-gsheet2tbl('https://docs.google.com/spreadsheets/d/1Z_4x3w2SgpOdHQ028IiPEgbB6CSFC0YT3oUymE5UoBE/edit?usp=sharing')
> Error in gsheet2text(url, format = "csv") : 
>   Unable to retrieve document. Is 'share by link' enabled for this sheet?
> sessionInfo()
> R version 3.2.5 (2016-04-14)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8  
 [6] LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gsheet_0.2.1

loaded via a namespace (and not attached):
 [1] httr_1.1.0    selectr_0.2-3 R6_2.1.2      magrittr_1.5  tools_3.2.5   curl_0.9.7    Rcpp_0.12.5   xml2_0.1.2    stringi_1.0-1
[10] stringr_1.0.0 rvest_0.3.1   XML_3.98-1.4

**Comment by florianduclot** [comment]
I too now encounter the same error with a code that used to work a few weeks ago.

After running the code in R/gsheet2text.R, I do have `page %>% rvest::html_nodes('script') %>% length() > 0 | page %>% rvest::html_nodes('style') %>% length() > 0` as TRUE.

For instance with the test and example spreadsheet: 
`url <- 'docs.google.com/spreadsheets/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo#gid=850032961'
`
I get the following:
https://gist.github.com/florianduclot/798c10ceaa822db88a7164fc2708bab0

**Comment by maxconway** [comment]
Hi, I've fixed this now, hopefully. It was due to a change in Google's URL formats.
To get the fixed version, install from github:
`devtools::install_github("maxconway/gsheet")`
Tell me if there are still any issues.
I'll push this fix to CRAN soon.
Max

**Comment by jbullock35** [comment]
Thank you, Max.  I just tried it on a fresh installation (R 3.3.0/Win 
x64), and it seemed to work well.

On my older R installations, I am getting the same error as before.  I 
haven't figured out the problems there.  But given that gsheet works 
with the fresh installation, the problems probably aren't due to gsheet.

Thank you again.  It's a very useful package.

John

**Comment by maxconway** [comment]
Hi John,
On the older installations, have you installed a fresh version from github? If so, tell me more about what exactly you're doing and I'll try to work out what's going on. In particular, it would be good if you could report your httr version, since I could imagine that and old version of that might be a possible cause.
Max

**Comment by maxconway** [comment]
Hi John,
Don't worry, I think I've fixed the issue you were seeing in your old versions now.
It was due to relying on a version of httr that was ahead of cran.
Max

**Comment by florianduclot** [comment]
Thank you @maxconway, it is fixed on my end as well.

**Comment by scrogster** [comment]
Thanks very much for the quick fix Max. 
All working perfectly now. 
Cheers,

MS.
