### ISSUE TITLE
Issue while reading

### ISSUE THREAD

**Issue by SomnathKadam** [maxconway/gsheet#7]
When I execute following command in R studio(Windows 7)

```
library(gsheet)
gsheet2tbl('docs.google.com/spreadsheets/d/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo')

```

It gives error like 

```
Error in gsheet2text(url, format = "csv") : 
   Unable to retrieve document. Is 'share by link' enabled for this sheet?
```

But this document is open in browser.

**Comment by maxconway** [comment]
Hi, I've fixed this now, hopefully. It was due to a change in Google's URL formats.
To get the fixed version, install from github:
`devtools::install_github("maxconway/gsheet")`
Tell me if there are still any issues.
I'll push this fix to CRAN soon.
Max
