### ISSUE TITLE
Issues with shiny/shinyapps.io?

### ISSUE THREAD

**Issue by mattbk** [maxconway/gsheet#8]
I'm trying to debug a small project and am wondering if anyone has reported issues with running `gsheet2tbl` on shinyapps.io. 

I'll report back if I figure out what the problem actually is.

**Comment by maxconway** [comment]
I'll need an error message and the context to try and diagnose an issue for sure, but I can't really think of any possible gsheet-specific issues on shinyapps.io, over and above just being able to access an outside website.

**Comment by mattbk** [comment]
You don't need to do anything, I'm going to create some really small dummy sheets to see if they load.

> being able to access an outside website.

Wondering if that is the case. We'll see.

**Comment by maxconway** [comment]
Tell me what you find out and I'll put it in an FAQ?

**Comment by mattbk** [comment]
Found it. Not an issue with `gsheet`. I switched from Shiny datatables to DT datatables and didn't realize I needed to add the `DT::` prefix on the UI as well (https://rstudio.github.io/DT/shiny.html).

Thanks for the great, easy-to-use package!
